language: node_js
node_js: stable
cache:
  directories:
  - node_modules
before_install:
  - export TZ='Asia/Shanghai'
  - openssl aes-256-cbc -K $encrypted_5268d366f252_key -iv $encrypted_5268d366f252_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - cp .travis/id_rsa ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - chmod 600 ~/.ssh/*
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - git config --global user.name "SakuraNaoc"
  - git config --global user.email "sakuranaoc@gmail.com"
  - git clone https://github.com/SakuraNaoc/blog.git
install:
  - npm install hexo -g
  - npm install hexo-renderer-jade hexo-renderer-stylus hexo-generator-search --save
script:
  - hexo clean
  - hexo g
  - hexo d
branches:
  only:
  - master
