language: node_js
node_js: stable
cache:
  directories:
  - node_modules
before_install:
  - export TZ='Asia/Shanghai' 
#  - openssl aes-256-cbc -K $encrypted_ec3bbb34470a_key -iv $encrypted_ec3bbb34470a_iv -in .travis/id_rsa_blog.enc -out .travis/id_rsa_blog -d
#  - cp .travis/id_rsa_blog ~/.ssh/id_rsa_blog
#  - cp .travis/ssh_config ~/.ssh/config
#  - chmod 600 ~/.ssh/*
#  - eval $(ssh-agent)
#  - ssh-add ~/.ssh/id_rsa_blog
  - git config --global user.name "SakuraNaoc"
  - git config --global user.email "sakuranaoc@gmail.com"
  - git clone https://github.com/SakuraNaoc/blog.git
install:
  - npm install hexo -g
script:
  - hexo clean
  - hexo g
#  - hexo d
branches:
  only:
  - master
